# Generated by Django 5.1.1 on 2024-10-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='City', max_length=255),
            preserve_default=False,
        ),
    ]
