# Generated by Django 5.1.1 on 2024-10-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyreviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyreviews',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='propertyreviews',
            name='rating',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
