# Generated by Django 5.1.1 on 2024-10-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_gender_client_partner_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='partner_age',
            field=models.IntegerField(default=0),
        ),
    ]
