# Generated by Django 5.1.1 on 2024-10-16 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_agent_id_remove_owner_id_alter_agent_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
