# Generated by Django 5.1.1 on 2024-10-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_agent_average_rating_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='caption',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
